/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pss1inventarioscunoc.frontend.vistas.bienes;

import pss1inventarioscunoc.frontend.vistas.*;
import java.math.RoundingMode;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import pss1inventarioscunoc.backend.controladores.ControladorBien;
import pss1inventarioscunoc.backend.controladores.ControladorEncargado;
import pss1inventarioscunoc.backend.enums.TipoDeBien;
import pss1inventarioscunoc.backend.enums.Vista;
import pss1inventarioscunoc.backend.pojos.Bien;
import pss1inventarioscunoc.backend.pojos.Encargado;
import pss1inventarioscunoc.backend.pojos.Factura;
import pss1inventarioscunoc.backend.pojos.Proveedor;
import pss1inventarioscunoc.frontend.vistas.facturas.ListadoDeFacturasJDialog;
import pss1inventarioscunoc.frontend.vistas.proveedores.ListadoDeProveedoresJDialog;

/**
 *
 * @author fabricio
 */
public class BienesJPanel1 extends javax.swing.JPanel {

    private Vista vista = Vista.BIENES_JPANEL1;
    private Encargado encargado = null;
    private ControladorBien controlador = null;
    public List<Encargado> listaEncargados = null;
    public ObservableList<Encargado> listaEncargadosObsr = null;

    private String nombre;
    private Proveedor proveedor;
    private Factura factura;

    public static final String PROP_NOMBRE = "nombre";

    /**
     * Creates new form ValidacionEncargado
     */
    public BienesJPanel1() {
        initComponents();
        this.setName("Bienes");
        this.controlador = new ControladorBien();
        this.listaEncargados = new LinkedList<>();
        this.listaEncargadosObsr = ObservableCollections.observableList(listaEncargados);
        this.actualizarLista();
        desactivarPaneles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelValidacion = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        curTextField6 = new javax.swing.JTextField();
        procedenciaTextField5 = new javax.swing.JTextField();
        descripcionTextField7 = new javax.swing.JTextField();
        divisionTextField9 = new javax.swing.JTextField();
        tipoBienComboBox = new javax.swing.JComboBox<>();
        guardarButton1 = new javax.swing.JButton();
        valorTextField10 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        facturaTextField10 = new javax.swing.JTextField();
        asignarFacturaButton2 = new javax.swing.JButton();
        trasladoPanel = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        seccionTextField17 = new javax.swing.JTextField();
        receptorTextField16 = new javax.swing.JTextField();
        fechajDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel34 = new javax.swing.JLabel();
        donacionjPanel6 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        correlativoTextField12 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        puntoTextField13 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        numeroActaTextField14 = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel1.setBackground(new java.awt.Color(51, 119, 180));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienes");

        jScrollPane2.setBackground(new java.awt.Color(51, 119, 180));

        panelValidacion.setBackground(new java.awt.Color(51, 119, 180));

        jPanel2.setBackground(new java.awt.Color(51, 119, 180));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingreso de datos del bien");

        jPanel8.setBackground(new java.awt.Color(51, 119, 180));

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Cur*:");

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Procedencia*:");

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Descripcion*:");

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Valor*:");

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Division*:");

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Tipo*:");

        curTextField6.setBackground(new java.awt.Color(255, 255, 255));
        curTextField6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        curTextField6.setForeground(new java.awt.Color(0, 0, 102));
        curTextField6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        procedenciaTextField5.setBackground(new java.awt.Color(255, 255, 255));
        procedenciaTextField5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        procedenciaTextField5.setForeground(new java.awt.Color(0, 0, 102));
        procedenciaTextField5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        descripcionTextField7.setBackground(new java.awt.Color(255, 255, 255));
        descripcionTextField7.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        descripcionTextField7.setForeground(new java.awt.Color(0, 0, 102));
        descripcionTextField7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        divisionTextField9.setBackground(new java.awt.Color(255, 255, 255));
        divisionTextField9.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        divisionTextField9.setForeground(new java.awt.Color(0, 0, 102));
        divisionTextField9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tipoBienComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*", "compra", "donacion", "traslado" }));
        tipoBienComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoBienComboBoxActionPerformed(evt);
            }
        });

        guardarButton1.setBackground(new java.awt.Color(255, 153, 0));
        guardarButton1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        guardarButton1.setForeground(new java.awt.Color(255, 255, 255));
        guardarButton1.setText("REGISTRAR BIEN");
        guardarButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        guardarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButton1ActionPerformed(evt);
            }
        });

        valorTextField10.setBackground(new java.awt.Color(255, 255, 255));
        valorTextField10.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        valorTextField10.setForeground(new java.awt.Color(0, 0, 102));
        valorTextField10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Factura*:");

        facturaTextField10.setBackground(new java.awt.Color(255, 255, 255));
        facturaTextField10.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        facturaTextField10.setForeground(new java.awt.Color(0, 0, 102));
        facturaTextField10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        facturaTextField10.setEnabled(false);

        asignarFacturaButton2.setBackground(new java.awt.Color(0, 204, 204));
        asignarFacturaButton2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        asignarFacturaButton2.setForeground(new java.awt.Color(255, 255, 255));
        asignarFacturaButton2.setText("Asignar factura");
        asignarFacturaButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        asignarFacturaButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarFacturaButton2ActionPerformed(evt);
            }
        });

        trasladoPanel.setBackground(new java.awt.Color(51, 119, 180));

        jLabel31.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Bien por Traslado");

        jLabel32.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Fecha:");

        jLabel33.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Seccion:");

        seccionTextField17.setBackground(new java.awt.Color(255, 255, 255));
        seccionTextField17.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        seccionTextField17.setForeground(new java.awt.Color(0, 0, 102));
        seccionTextField17.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        receptorTextField16.setBackground(new java.awt.Color(255, 255, 255));
        receptorTextField16.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        receptorTextField16.setForeground(new java.awt.Color(0, 0, 102));
        receptorTextField16.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel34.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Receptor:");

        javax.swing.GroupLayout trasladoPanelLayout = new javax.swing.GroupLayout(trasladoPanel);
        trasladoPanel.setLayout(trasladoPanelLayout);
        trasladoPanelLayout.setHorizontalGroup(
            trasladoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trasladoPanelLayout.createSequentialGroup()
                .addGroup(trasladoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel32)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(trasladoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trasladoPanelLayout.createSequentialGroup()
                        .addComponent(fechajDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(trasladoPanelLayout.createSequentialGroup()
                        .addGroup(trasladoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seccionTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(receptorTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trasladoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(175, 175, 175))
        );
        trasladoPanelLayout.setVerticalGroup(
            trasladoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trasladoPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel32)
                .addGap(93, 93, 93))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trasladoPanelLayout.createSequentialGroup()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechajDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(trasladoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seccionTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(trasladoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receptorTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)))
        );

        donacionjPanel6.setBackground(new java.awt.Color(51, 119, 180));

        jLabel28.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Correlativo:");

        jLabel27.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Bien por Donacion");

        correlativoTextField12.setBackground(new java.awt.Color(255, 255, 255));
        correlativoTextField12.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        correlativoTextField12.setForeground(new java.awt.Color(0, 0, 102));
        correlativoTextField12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel29.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Punto:");

        puntoTextField13.setBackground(new java.awt.Color(255, 255, 255));
        puntoTextField13.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        puntoTextField13.setForeground(new java.awt.Color(0, 0, 102));
        puntoTextField13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel30.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Numero de acta:");

        numeroActaTextField14.setBackground(new java.awt.Color(255, 255, 255));
        numeroActaTextField14.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        numeroActaTextField14.setForeground(new java.awt.Color(0, 0, 102));
        numeroActaTextField14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout donacionjPanel6Layout = new javax.swing.GroupLayout(donacionjPanel6);
        donacionjPanel6.setLayout(donacionjPanel6Layout);
        donacionjPanel6Layout.setHorizontalGroup(
            donacionjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donacionjPanel6Layout.createSequentialGroup()
                .addGroup(donacionjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(donacionjPanel6Layout.createSequentialGroup()
                        .addGroup(donacionjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, donacionjPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(donacionjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(correlativoTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puntoTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroActaTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, donacionjPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(154, 154, 154))
        );
        donacionjPanel6Layout.setVerticalGroup(
            donacionjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donacionjPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(donacionjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(correlativoTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(donacionjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(puntoTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(donacionjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroActaTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel18)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel21))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tipoBienComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(procedenciaTextField5)
                            .addComponent(curTextField6)
                            .addComponent(descripcionTextField7)
                            .addComponent(divisionTextField9)
                            .addComponent(valorTextField10)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(facturaTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(asignarFacturaButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel24)
                    .addComponent(donacionjPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(guardarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(trasladoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(curTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tipoBienComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(descripcionTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(valorTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(divisionTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(procedenciaTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(facturaTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(asignarFacturaButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(donacionjPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(trasladoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(guardarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelValidacionLayout = new javax.swing.GroupLayout(panelValidacion);
        panelValidacion.setLayout(panelValidacionLayout);
        panelValidacionLayout.setHorizontalGroup(
            panelValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValidacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(755, Short.MAX_VALUE))
        );
        panelValidacionLayout.setVerticalGroup(
            panelValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValidacionLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(panelValidacion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 722, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guardarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButton1ActionPerformed
        //Validadndo valor
        String tipoDeBien = this.tipoBienComboBox.getSelectedItem().toString();
        int numeroFactura = ControladorBien.ID_FACTURA_INEXISTENTE;
        ArrayList<String> datos = new ArrayList<>();
        datos.add(curTextField6.getText());
        datos.add(procedenciaTextField5.getText());
        datos.add(descripcionTextField7.getText());
        datos.add(divisionTextField9.getText());
        boolean verValores = controlador.verificarDatosGeneralesBien(datos, valorTextField10.getText());
        if (verValores) {
            if (factura != null) {
                numeroFactura = factura.getIdFactura();
            }
            if (tipoDeBien.equalsIgnoreCase("traslado")) {
                boolean verificacionTraslado = controlador.verificarDatosTraslado(this.fechajDateChooser1.getDate(), seccionTextField17.getText(), receptorTextField16.getText());
                if (verificacionTraslado) {
                    Bien bien = new Bien(this.curTextField6.getText(), numeroFactura, this.procedenciaTextField5.getText(), '1', this.descripcionTextField7.getText(), TipoDeBien.TRASLADO, Double.valueOf(valorTextField10.getText()), divisionTextField9.getText(), new Timestamp(this.fechajDateChooser1.getDate().getTime()), '1', this.seccionTextField17.getText(), this.receptorTextField16.getText());
                    registrarBien(bien);
                }
            } else if (tipoDeBien.equalsIgnoreCase("donacion")) {
                boolean verificacionDonacion = controlador.verificarDatosDonacion(this.correlativoTextField12.getText(), this.puntoTextField13.getText(), this.numeroActaTextField14.getText());
                if (verificacionDonacion) {
                    Bien bien = new Bien(this.curTextField6.getText(), numeroFactura, this.procedenciaTextField5.getText(), '1', this.descripcionTextField7.getText(), TipoDeBien.DONACION, Double.valueOf(this.valorTextField10.getText()), this.divisionTextField9.getText(), Integer.valueOf(this.correlativoTextField12.getText()), this.puntoTextField13.getText(), Integer.valueOf(this.numeroActaTextField14.getText()));
                    registrarBien(bien);
                }
            } else if (tipoDeBien.equalsIgnoreCase("compra")) {
                Bien bien = new Bien(this.curTextField6.getText(), numeroFactura, this.procedenciaTextField5.getText(), '1', this.descripcionTextField7.getText(), TipoDeBien.COMPRA, Double.valueOf(this.valorTextField10.getText()), this.divisionTextField9.getText());
                registrarBien(bien);
            } else {
                JOptionPane.showMessageDialog(this, "No ha seleccionado un tipo de bien", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        }


    }//GEN-LAST:event_guardarButton1ActionPerformed

    private void tipoBienComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoBienComboBoxActionPerformed
        String bien = this.tipoBienComboBox.getSelectedItem().toString();
        if (bien.equalsIgnoreCase("compra")) {
            this.donacionjPanel6.setVisible(false);
            this.trasladoPanel.setVisible(false);
        } else if (bien.equalsIgnoreCase("donacion")) {
            this.donacionjPanel6.setVisible(true);
            this.trasladoPanel.setVisible(false);
        } else if (bien.equalsIgnoreCase("traslado")) {//Traslado
            this.donacionjPanel6.setVisible(false);
            this.trasladoPanel.setVisible(true);
        } else {
            desactivarPaneles();
        }
    }//GEN-LAST:event_tipoBienComboBoxActionPerformed

    private void asignarFacturaButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarFacturaButton2ActionPerformed
        ListadoDeFacturasJDialog listado = new ListadoDeFacturasJDialog(null, true, this);
        listado.setVisible(true);
    }//GEN-LAST:event_asignarFacturaButton2ActionPerformed

    private void actualizarLista() {
//        this.controlador.actualizarEncargadosValidacionEncargados(this);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asignarFacturaButton2;
    private javax.swing.JTextField correlativoTextField12;
    private javax.swing.JTextField curTextField6;
    private javax.swing.JTextField descripcionTextField7;
    private javax.swing.JTextField divisionTextField9;
    private javax.swing.JPanel donacionjPanel6;
    private javax.swing.JTextField facturaTextField10;
    private com.toedter.calendar.JDateChooser fechajDateChooser1;
    private javax.swing.JButton guardarButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField numeroActaTextField14;
    private javax.swing.JPanel panelValidacion;
    private javax.swing.JTextField procedenciaTextField5;
    private javax.swing.JTextField puntoTextField13;
    private javax.swing.JTextField receptorTextField16;
    private javax.swing.JTextField seccionTextField17;
    private javax.swing.JComboBox<String> tipoBienComboBox;
    private javax.swing.JPanel trasladoPanel;
    private javax.swing.JTextField valorTextField10;
    // End of variables declaration//GEN-END:variables

    private void registrarBien(Bien bien) {
        if (controlador.registrarBien(bien)) {
            JOptionPane.showMessageDialog(this, "Se registro el bien");
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar el bien", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiarCampos() {
        this.curTextField6.setText("");
        this.descripcionTextField7.setText("");
        this.valorTextField10.setText("");
        this.divisionTextField9.setText("");
        this.procedenciaTextField5.setText("");
        this.facturaTextField10.setText("");
        this.factura = null;
        this.correlativoTextField12.setText("");
        this.puntoTextField13.setText("");
        this.numeroActaTextField14.setText("");
        this.seccionTextField17.setText("");
        this.receptorTextField16.setText("");
    }

    private void desactivarPaneles() {
        this.trasladoPanel.setVisible(false);
        this.donacionjPanel6.setVisible(false);
    }

    private void eliminarFactura() {
        this.factura = null;
        this.facturaTextField10.setText("");
    }

    public Factura getFactura() {
        return factura;
    }

    public void setFactura(Factura factura) {
        this.factura = factura;
    }

    public JTextField getFacturaTextField10() {
        return facturaTextField10;
    }

    public void setFacturaTextField10(JTextField facturaTextField10) {
        this.facturaTextField10 = facturaTextField10;
    }

    public Vista getVista() {
        return vista;
    }

}
