/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pss1inventarioscunoc.frontend.vistas.proveedores;

import com.sun.javafx.scene.control.skin.VirtualFlow;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import pss1inventarioscunoc.backend.controladores.ControladorProveedor;
import pss1inventarioscunoc.backend.pojos.Proveedor;
import pss1inventarioscunoc.frontend.vistas.bienes.BienesJPanel1;
import pss1inventarioscunoc.frontend.vistas.facturas.FacturasJPanel;
import pss1inventarioscunoc.frontend.vistas.facturas.ModificarFacturasDialog;

/**
 *
 * @author jesfrin
 */
public class ListadoDeProveedoresJDialog extends javax.swing.JDialog {

    private ControladorProveedor controlador = null;
    public List<Proveedor> listaProveedores = null;
    public ObservableList<Proveedor> listaProveedoresObs = null;
    private Proveedor proveedor;
    private FacturasJPanel panelFacturas;
    private ModificarFacturasDialog modiFacturasDialog;

    /**
     * Creates new form listadoDeProveedoresJDialog
     */
    public ListadoDeProveedoresJDialog(java.awt.Frame parent, boolean modal, FacturasJPanel facturasPanel) {
        super(parent, modal);
        this.controlador = new ControladorProveedor();
        this.listaProveedores = new LinkedList<>();
        this.listaProveedoresObs = ObservableCollections.observableList(listaProveedores);
        this.actualizarLista(controlador.buscarProveedores());
        this.proveedor = new Proveedor();
        this.panelFacturas = facturasPanel;
        initComponents();
    }
    
    
        public ListadoDeProveedoresJDialog(java.awt.Frame parent, boolean modal, ModificarFacturasDialog modiFacturasDialog) {
        super(parent, modal);
        this.controlador = new ControladorProveedor();
        this.listaProveedores = new LinkedList<>();
        this.listaProveedoresObs = ObservableCollections.observableList(listaProveedores);
        this.actualizarLista(controlador.buscarProveedores());
        this.proveedor = new Proveedor();
        this.modiFacturasDialog = modiFacturasDialog;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        seleccionarProveedorjButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Seleccione su proveedor");

        seleccionarProveedorjButton1.setText("Seleccionar Proveedor");
        seleccionarProveedorjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarProveedorjButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${listaProveedoresObs}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTable2);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombreDeProveedor}"));
        columnBinding.setColumnName("Nombre De Proveedor");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${correoElectronico}"));
        columnBinding.setColumnName("Correo Electronico");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descripcion}"));
        columnBinding.setColumnName("Descripcion");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${direccion}"));
        columnBinding.setColumnName("Direccion");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nit}"));
        columnBinding.setColumnName("Nit");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${proveedor}"), jTable2, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(485, 485, 485)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(511, 511, 511)
                        .addComponent(seleccionarProveedorjButton1)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(seleccionarProveedorjButton1)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarProveedorjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarProveedorjButton1ActionPerformed
        if (panelFacturas != null) {
            this.panelFacturas.setProveedor(this.proveedor);
            this.panelFacturas.getProveedorTextField5().setText(this.proveedor.getNombreDeProveedor());

        }else if(modiFacturasDialog!=null){
            this.modiFacturasDialog.setProveedor(proveedor);
            this.modiFacturasDialog.getProveedorTextField5().setText(this.proveedor.getNombreDeProveedor());
        }
        JOptionPane.showMessageDialog(this, "Proveedor seleccionado:" + this.proveedor.getNombreDeProveedor());
        this.dispose();
    }//GEN-LAST:event_seleccionarProveedorjButton1ActionPerformed

    private void actualizarLista(List<Proveedor> listado) {
        listaProveedoresObs.clear();
        listaProveedoresObs.addAll((List<Proveedor>) (List<?>) listado);
    }

    public ObservableList<Proveedor> getListaProveedoresObs() {
        return listaProveedoresObs;
    }

    public void setListaProveedoresObs(ObservableList<Proveedor> listaProveedoresObs) {
        this.listaProveedoresObs = listaProveedoresObs;
    }

    public Proveedor getProveedor() {
        return proveedor;
    }

    public void setProveedor(Proveedor proveedor) {
        if (proveedor != null) {
            this.seleccionarProveedorjButton1.setEnabled(true);
            this.proveedor = proveedor;
        } else {
            this.seleccionarProveedorjButton1.setEnabled(false);
            this.proveedor = null;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton seleccionarProveedorjButton1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
