/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pss1inventarioscunoc.frontend.vistas.proveedores;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import pss1inventarioscunoc.backend.controladores.ControladorProveedor;
import pss1inventarioscunoc.backend.enums.Vista;
import pss1inventarioscunoc.backend.pojos.Proveedor;

/**
 *
 * @author jesfrin
 */
public class ModificarProveedorJDialog extends javax.swing.JDialog {

    private Vista vista = Vista.MODIFICAR_PROVEEDOR_JDIALOG;
    private Proveedor proveedor;
    private ControladorProveedor controlador;

    /**
     * Creates new form ModificarProveedorJDialog
     */
    public ModificarProveedorJDialog(java.awt.Frame parent, boolean modal, Proveedor proveedor, ControladorProveedor controlador) {
        super(parent, modal);
        this.proveedor = proveedor;
        this.controlador = controlador;
        this.setLocationRelativeTo(this);
        initComponents();
        iniciarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        guardarButton1 = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        nitTextField = new javax.swing.JTextField();
        nombreTextField1 = new javax.swing.JTextField();
        direccionTextField2 = new javax.swing.JTextField();
        correoElectronicoTextField3 = new javax.swing.JTextField();
        descripcionTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(51, 119, 180));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("Nombre*");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("Nit*");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("Direccion*");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel15.setText("Descripcion*");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel16.setText("Correo electronico");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Modificar Proveedor");

        guardarButton1.setBackground(new java.awt.Color(255, 153, 0));
        guardarButton1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        guardarButton1.setText("GUARDAR");
        guardarButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        guardarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButton1ActionPerformed(evt);
            }
        });

        cancelarButton.setBackground(new java.awt.Color(0, 204, 204));
        cancelarButton.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        cancelarButton.setText("CANCELAR");
        cancelarButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        nitTextField.setBackground(new java.awt.Color(255, 255, 255));
        nitTextField.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        nitTextField.setForeground(new java.awt.Color(0, 0, 102));
        nitTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        nombreTextField1.setBackground(new java.awt.Color(255, 255, 255));
        nombreTextField1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        nombreTextField1.setForeground(new java.awt.Color(0, 0, 102));
        nombreTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        direccionTextField2.setBackground(new java.awt.Color(255, 255, 255));
        direccionTextField2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        direccionTextField2.setForeground(new java.awt.Color(0, 0, 102));
        direccionTextField2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        correoElectronicoTextField3.setBackground(new java.awt.Color(255, 255, 255));
        correoElectronicoTextField3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        correoElectronicoTextField3.setForeground(new java.awt.Color(0, 0, 102));
        correoElectronicoTextField3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        correoElectronicoTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoElectronicoTextField3ActionPerformed(evt);
            }
        });

        descripcionTextField4.setBackground(new java.awt.Color(255, 255, 255));
        descripcionTextField4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        descripcionTextField4.setForeground(new java.awt.Color(0, 0, 102));
        descripcionTextField4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descripcionTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correoElectronicoTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(guardarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(212, 212, 212))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(nombreTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(nitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addGap(9, 9, 9))
                    .addComponent(direccionTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcionTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoElectronicoTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButton1ActionPerformed
        ArrayList<String> datos = new ArrayList<>();
        datos.add(this.nombreTextField1.getText());
        datos.add(this.nitTextField.getText());
        datos.add(this.direccionTextField2.getText());
        datos.add(this.descripcionTextField4.getText());
        if (!controlador.verificarDatosProveedor(datos)) {
            JOptionPane.showMessageDialog(this,
                    "Faltan datos para poder crear un proveedor",
                    "Datos incompletos",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            boolean seRegistro = controlador.modificarProveedor(new Proveedor(proveedor.getIdProveedor(),this.nombreTextField1.getText(), this.nitTextField.getText(), this.direccionTextField2.getText(), this.descripcionTextField4.getText(), this.correoElectronicoTextField3.getText()));
            if (seRegistro) {
                JOptionPane.showMessageDialog(this,
                        "Proveedor Actualizado");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this,
                        "No se ha podido actualizar el proveedor",
                        "Error Interno",
                        JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_guardarButton1ActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void correoElectronicoTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoElectronicoTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoElectronicoTextField3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField correoElectronicoTextField3;
    private javax.swing.JTextField descripcionTextField4;
    private javax.swing.JTextField direccionTextField2;
    private javax.swing.JButton guardarButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nitTextField;
    private javax.swing.JTextField nombreTextField1;
    // End of variables declaration//GEN-END:variables

    private void iniciarCampos() {
        this.nombreTextField1.setText(proveedor.getNombreDeProveedor());
        this.nitTextField.setText(proveedor.getNit());
        this.direccionTextField2.setText(proveedor.getDireccion());
        this.descripcionTextField4.setText(proveedor.getDescripcion());
        this.correoElectronicoTextField3.setText(proveedor.getCorreoElectronico());
    }

    public Vista getVista() {
        return vista;
    }

}
