/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pss1inventarioscunoc.frontend.vistas.facturas;

import java.sql.Timestamp;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import pss1inventarioscunoc.backend.controladores.ControladorFactura;
import pss1inventarioscunoc.backend.enums.Vista;
import pss1inventarioscunoc.backend.pojos.Factura;
import pss1inventarioscunoc.frontend.tarjetasresponsabilidad.ModificacionTarjetaResponsabilidad;
import pss1inventarioscunoc.frontend.vistas.ConsultaBienes;
import pss1inventarioscunoc.frontend.vistas.bienes.BienesJPanel1;

/**
 *
 * @author jesfrin
 */
public class ListadoDeFacturasJDialog extends javax.swing.JDialog {

    private Vista vista = Vista.LISTADO_DE_FACTURAS_JDIALOG;
    private ControladorFactura controlador;
    public List<Factura> listaFacturas;
    public ObservableList<Factura> listaObservableFacturas;
    private Factura factura;
    private BienesJPanel1 bienPanel;
    private ConsultaBienes consultaBienes;
    private ModificacionTarjetaResponsabilidad mtr;

    /**
     * Creates new form listadoDeFacturasJDialog
     */
    public ListadoDeFacturasJDialog(java.awt.Frame parent, boolean modal, BienesJPanel1 bienPanel) {
        super(parent, modal);
        this.bienPanel = bienPanel;
        this.controlador = new ControladorFactura();
        this.factura = null;
        this.listaFacturas = new LinkedList<>();
        this.listaObservableFacturas = ObservableCollections.observableList(listaFacturas);
        actualizarLista(controlador.buscarFacturas());
        this.consultaBienes = null;
        initComponents();
    }

    public ListadoDeFacturasJDialog(java.awt.Frame parent, boolean modal, ConsultaBienes consultaBienes) {
        super(parent, modal);
        this.consultaBienes = consultaBienes;
        this.controlador = new ControladorFactura();
        this.factura = null;
        this.listaFacturas = new LinkedList<>();
        this.listaObservableFacturas = ObservableCollections.observableList(listaFacturas);
        actualizarLista(controlador.buscarFacturas());
        this.bienPanel = null;
        initComponents();
    }
    
    public ListadoDeFacturasJDialog(java.awt.Frame parent, boolean modal, ModificacionTarjetaResponsabilidad mtr) {
        super(parent, modal);
        this.mtr = mtr;
        this.controlador = new ControladorFactura();
        this.factura = null;
        this.listaFacturas = new LinkedList<>();
        this.listaObservableFacturas = ObservableCollections.observableList(listaFacturas);
        actualizarLista(controlador.buscarFacturas());
        this.bienPanel = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        facturasjTable1 = new javax.swing.JTable();
        seleccionarFacturajButton1 = new javax.swing.JButton();
        fecha1jDateChooser1 = new com.toedter.calendar.JDateChooser();
        fecha2jDateChooser2 = new com.toedter.calendar.JDateChooser();
        proveedorTextField11 = new javax.swing.JTextField();
        opcionBusquedajComboBox1 = new javax.swing.JComboBox<>();
        buscarButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 119, 180));

        jLabel1.setText("Facturas del sistema");

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${listaObservableFacturas}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, facturasjTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descripcion}"));
        columnBinding.setColumnName("Descripcion");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fecha}"));
        columnBinding.setColumnName("Fecha");
        columnBinding.setColumnClass(java.sql.Timestamp.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombreProveedor}"));
        columnBinding.setColumnName("Proveedor");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numeroFactura}"));
        columnBinding.setColumnName("factura");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valor}"));
        columnBinding.setColumnName("Valor");
        columnBinding.setColumnClass(Double.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${factura}"), facturasjTable1, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(facturasjTable1);

        seleccionarFacturajButton1.setText("Seleccionar factura");
        seleccionarFacturajButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarFacturajButton1ActionPerformed(evt);
            }
        });

        proveedorTextField11.setBackground(new java.awt.Color(255, 255, 255));
        proveedorTextField11.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        proveedorTextField11.setForeground(new java.awt.Color(0, 0, 102));
        proveedorTextField11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        opcionBusquedajComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "proveedor", "fecha" }));

        buscarButton1.setBackground(new java.awt.Color(255, 153, 0));
        buscarButton1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        buscarButton1.setForeground(new java.awt.Color(255, 255, 255));
        buscarButton1.setText("Buscar");
        buscarButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buscarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(seleccionarFacturajButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(fecha1jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fecha2jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(proveedorTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(opcionBusquedajComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(opcionBusquedajComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buscarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proveedorTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fecha1jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fecha2jDateChooser2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(seleccionarFacturajButton1)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarFacturajButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarFacturajButton1ActionPerformed
        if (bienPanel != null) {
            this.bienPanel.setFactura(this.factura);
            this.bienPanel.getFacturaTextField10().setText(this.factura.getDescripcion());
        } else if (mtr != null){
            this.mtr.setSelectedFactura(factura);
            this.mtr.getNoFacturaTextField().setText(Integer.toString(mtr.getSelectedFactura().getIdFactura()));
            this.mtr.setFacturaButtonSelected(true);
        } else{
            this.consultaBienes.setFactura(factura);
            this.consultaBienes.getFacturaTextField10().setText(this.factura.getDescripcion());
        }

        JOptionPane.showMessageDialog(this, "Descripcion factura seleccionada:" + this.factura.getDescripcion());
        this.dispose();
    }//GEN-LAST:event_seleccionarFacturajButton1ActionPerformed

    private void buscarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButton1ActionPerformed
        String opcion = this.opcionBusquedajComboBox1.getSelectedItem().toString();
        if (opcion.equalsIgnoreCase("proveedor")) {
            if (!this.proveedorTextField11.getText().isEmpty()) {
                actualizarLista(controlador.buscarFacturas(this.proveedorTextField11.getText()));
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese el nombre de un proveedor", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            Timestamp fecha1 = new Timestamp(this.fecha1jDateChooser1.getDate().getTime());
            Timestamp fecha2 = new Timestamp(this.fecha2jDateChooser2.getDate().getTime());
            System.out.println();
            if (fecha1 != null && fecha2 != null) {
                actualizarLista(controlador.buscarFacturas(fecha1, fecha2));
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese fecha incio y final", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_buscarButton1ActionPerformed

    private void actualizarLista(List<Factura> listado) {
        listaObservableFacturas.clear();
        listaObservableFacturas.addAll((List<Factura>) (List<?>) listado);
    }

    public ObservableList<Factura> getListaObservableFacturas() {
        return listaObservableFacturas;
    }

    public void setListaObservableFacturas(ObservableList<Factura> listaObservableFacturas) {
        this.listaObservableFacturas = listaObservableFacturas;
    }

    public Factura getFactura() {
        return factura;
    }

    public void setFactura(Factura factura) {
        if (factura != null) {
            this.seleccionarFacturajButton1.setEnabled(true);
            this.factura = factura;
        } else {
            this.seleccionarFacturajButton1.setEnabled(false);
            this.factura = null;
        }
    }

    public Vista getVista() {
        return vista;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton1;
    private javax.swing.JTable facturasjTable1;
    private com.toedter.calendar.JDateChooser fecha1jDateChooser1;
    private com.toedter.calendar.JDateChooser fecha2jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> opcionBusquedajComboBox1;
    private javax.swing.JTextField proveedorTextField11;
    private javax.swing.JButton seleccionarFacturajButton1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
