/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pss1inventarioscunoc.frontend.tarjetasresponsabilidad;
import com.toedter.calendar.JDateChooser;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JTextField;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import pss1inventarioscunoc.backend.controladores.*;
import pss1inventarioscunoc.backend.enums.GrupoVista;
import pss1inventarioscunoc.backend.enums.Vista;
import pss1inventarioscunoc.backend.pojos.*;
import pss1inventarioscunoc.frontend.vistas.facturas.ListadoDeFacturasJDialog;

/**
 *
 * @author fabricio
 */
public class ModificacionTarjetaResponsabilidad extends javax.swing.JPanel {

    public static String DEFAULT_TEXT_SIN_ASIGNAR = "Sin asignar";
    private Vista vista = Vista.MODIFICACION_TARJETAS;
    public LinkedList<Encargado> listaEncargados = null;
    public ObservableList<Encargado> listaEncargadosObsr = null;
    public LinkedList<TarjetaResponsabilidad> listaTarjetas = null;
    public ObservableList<TarjetaResponsabilidad> listaTarjetasObsr = null;
    public LinkedList<Proveedor> listaProveedores = null;
    public ObservableList<Proveedor> listaProveedoresObsr = null;
    private Encargado selectedEncargado = null;
    private TarjetaResponsabilidad selectedTarjeta = null;
    private Proveedor selectedProveedor = null;
    private Factura selectedFactura = null;
    private ControladorEncargado controladorEncargado = null;
    private ControladorTarjetaResponsabilidad controladorTarjeta = null;
    private ControladorProveedor controladorProveedor = null;
    private boolean tableEncargadosSelected = false;
    private boolean tableTarjetasSelected = false;
    private boolean tableProveedoresSelected = false;
    private boolean facturaButtonSelected = false;
    
    /**
     * Creates new form ValidacionEncargado
     */
    public ModificacionTarjetaResponsabilidad() {
        this.iniciarlizar();
        this.initComponents();
        this.setName("Modificacion");
        this.actualizarLista();
        this.noFacturaTextField.setEditable(false);
        this.selectedProveedorLabel.setText(DEFAULT_TEXT_SIN_ASIGNAR);
        this.selectedEncargadoLabel.setText(DEFAULT_TEXT_SIN_ASIGNAR);
        this.noFacturaTextField.setText(DEFAULT_TEXT_SIN_ASIGNAR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        panelValidacion = new javax.swing.JPanel();
        tablaEncargados = new javax.swing.JLabel();
        actualizarButton = new javax.swing.JButton();
        actualizarTablasButton = new javax.swing.JButton();
        limpiarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEncargado = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTarjetas = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        noFacturaTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        selectedProveedorLabel = new javax.swing.JLabel();
        selectedEncargadoLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        cambiarFacturaButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 119, 180));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Modificación de Tarjetas de Responsabilidad");

        panelValidacion.setBackground(new java.awt.Color(51, 119, 180));

        tablaEncargados.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tablaEncargados.setText("Proveedores Disponibles");

        actualizarButton.setBackground(new java.awt.Color(51, 204, 0));
        actualizarButton.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        actualizarButton.setText("ACTUALIZAR");
        actualizarButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        actualizarButton.setEnabled(false);
        actualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarButtonActionPerformed(evt);
            }
        });

        actualizarTablasButton.setBackground(new java.awt.Color(255, 153, 0));
        actualizarTablasButton.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        actualizarTablasButton.setText("REFRESCAR");
        actualizarTablasButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        actualizarTablasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarTablasButtonActionPerformed(evt);
            }
        });

        limpiarButton.setBackground(new java.awt.Color(0, 204, 204));
        limpiarButton.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        limpiarButton.setText("CANCELAR");
        limpiarButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        limpiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarButtonActionPerformed(evt);
            }
        });

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${listaEncargadosObsr}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tablaEncargado);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Long.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombre}"));
        columnBinding.setColumnName("Nombre");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cargo}"));
        columnBinding.setColumnName("Cargo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${division}"));
        columnBinding.setColumnName("Division");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${selectedEncargado}"), tablaEncargado, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        tablaEncargado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEncargadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEncargado);

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${listaTarjetasObsr}");
        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tablaTarjetas);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Long.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${curBien}"));
        columnBinding.setColumnName("Cur Bien");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descripcion}"));
        columnBinding.setColumnName("Descripcion");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idProveedor}"));
        columnBinding.setColumnName("Id Proveedor");
        columnBinding.setColumnClass(Long.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idResponsable}"));
        columnBinding.setColumnName("Id Responsable");
        columnBinding.setColumnClass(Long.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${noFactura}"));
        columnBinding.setColumnName("No Factura");
        columnBinding.setColumnClass(Long.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${noOrdenCompra}"));
        columnBinding.setColumnName("No Orden Compra");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${selectedTarjeta}"), tablaTarjetas, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        tablaTarjetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaTarjetasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaTarjetas);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Tarjetas de Responsabilidad");

        noFacturaTextField.setBackground(new java.awt.Color(255, 255, 255));
        noFacturaTextField.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        noFacturaTextField.setForeground(new java.awt.Color(0, 0, 102));
        noFacturaTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Proveedor:");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Encargado:");

        selectedProveedorLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        selectedProveedorLabel.setText("Sin seleccionar");

        selectedEncargadoLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        selectedEncargadoLabel.setText("Sin seleccionar");

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${listaProveedoresObsr}");
        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tablaProveedores);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nit}"));
        columnBinding.setColumnName("Nit");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombreDeProveedor}"));
        columnBinding.setColumnName("Nombre");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descripcion}"));
        columnBinding.setColumnName("Descripcion");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${direccion}"));
        columnBinding.setColumnName("Direccion");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${correoElectronico}"));
        columnBinding.setColumnName("Correo Electronico");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${selectedProveedor}"), tablaProveedores, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        tablaProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProveedoresMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaProveedores);

        cambiarFacturaButton.setBackground(new java.awt.Color(0, 204, 204));
        cambiarFacturaButton.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        cambiarFacturaButton.setText("Cambiar factura");
        cambiarFacturaButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cambiarFacturaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarFacturaButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Encargados disponibles");

        javax.swing.GroupLayout panelValidacionLayout = new javax.swing.GroupLayout(panelValidacion);
        panelValidacion.setLayout(panelValidacionLayout);
        panelValidacionLayout.setHorizontalGroup(
            panelValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValidacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelValidacionLayout.createSequentialGroup()
                        .addGroup(panelValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(panelValidacionLayout.createSequentialGroup()
                                .addComponent(limpiarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(actualizarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(37, 37, 37)
                                .addComponent(actualizarTablasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelValidacionLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(47, 47, 47)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(panelValidacionLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelValidacionLayout.createSequentialGroup()
                                        .addComponent(selectedEncargadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(selectedProveedorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelValidacionLayout.createSequentialGroup()
                                        .addComponent(noFacturaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cambiarFacturaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tablaEncargados))))
                        .addGap(12, 12, 12))
                    .addGroup(panelValidacionLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelValidacionLayout.setVerticalGroup(
            panelValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelValidacionLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addGroup(panelValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectedEncargadoLabel)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(selectedProveedorLabel)
                    .addComponent(noFacturaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cambiarFacturaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablaEncargados, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(panelValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(panelValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limpiarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualizarTablasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addComponent(panelValidacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelValidacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarLista(){
        this.controladorEncargado.actualizarEncargadosCambioEncargadoBien(this);
        this.controladorTarjeta.actualizarTarjetasModificacionTarjetaResponsabilidad(this);
        this.controladorProveedor.actualizarProveedoresModificacionTarjetaResponsabilidad(this);
    }
    
    private void limpiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarButtonActionPerformed
        this.controladorEncargado.limpiarButtonCambioEncargadoBien(this);
    }//GEN-LAST:event_limpiarButtonActionPerformed

    private void actualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarButtonActionPerformed
        this.controladorTarjeta.actualizarButtonCambioEncargadoBien(this);
    }//GEN-LAST:event_actualizarButtonActionPerformed

    private void actualizarTablasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarTablasButtonActionPerformed
        this.actualizarLista();
        this.controladorEncargado.limpiarButtonCambioEncargadoBien(this);
    }//GEN-LAST:event_actualizarTablasButtonActionPerformed

    private void tablaEncargadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEncargadoMouseClicked
        this.controladorEncargado.tablaEncargadosMouseClickedCambioEncargadoBien(this);
    }//GEN-LAST:event_tablaEncargadoMouseClicked

    private void tablaTarjetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTarjetasMouseClicked
        this.controladorTarjeta.tablaTarjetasMouseClickedCambioEncargadoBien(this);
    }//GEN-LAST:event_tablaTarjetasMouseClicked

    private void tablaProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProveedoresMouseClicked
        this.controladorProveedor.tablaProveedoresMouseClickedModificacionTarjetaResponsabilidad(this);
    }//GEN-LAST:event_tablaProveedoresMouseClicked

    private void cambiarFacturaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarFacturaButtonActionPerformed
        ListadoDeFacturasJDialog listado = new ListadoDeFacturasJDialog(null, true, this);
        listado.setVisible(true);
    }//GEN-LAST:event_cambiarFacturaButtonActionPerformed


    public boolean isTableSelected() {
        return tableEncargadosSelected;
    }

    public void setTableSelected(boolean tableSelected) {
        this.tableEncargadosSelected = tableSelected;
    }

    public JButton getEliminarButton() {
        return actualizarTablasButton;
    }

    public JButton getActualizarButton() {
        return actualizarButton;
    }

    public JButton getLimpiarButton() {
        return limpiarButton;
    }

    public LinkedList<Encargado> getListaEncargados() {
        return listaEncargados;
    }

    public void setListaEncargados(LinkedList<Encargado> listaEncargados) {
        this.listaEncargados = listaEncargados;
    }

    public LinkedList<TarjetaResponsabilidad> getListaTarjetas() {
        return listaTarjetas;
    }

    public void setListaTarjetas(LinkedList<TarjetaResponsabilidad> listaTarjetas) {
        this.listaTarjetas = listaTarjetas;
    }

    public ObservableList<TarjetaResponsabilidad> getListaTarjetasObsr() {
        return listaTarjetasObsr;
    }

    public void setListaTarjetasObsr(ObservableList<TarjetaResponsabilidad> listaTarjetasObsr) {
        this.listaTarjetasObsr = listaTarjetasObsr;
    }

    public LinkedList<Proveedor> getListaProveedores() {
        return listaProveedores;
    }

    public void setListaProveedores(LinkedList<Proveedor> listaProveedores) {
        this.listaProveedores = listaProveedores;
    }

    public ObservableList<Proveedor> getListaProveedoresObsr() {
        return listaProveedoresObsr;
    }

    public void setListaProveedoresObsr(ObservableList<Proveedor> listaProveedoresObsr) {
        this.listaProveedoresObsr = listaProveedoresObsr;
    }

    public ObservableList<Encargado> getListaEncargadosObsr() {
        return listaEncargadosObsr;
    }

    public void setListaEncargadosObsr(ObservableList<Encargado> listaEncargadosObsr) {
        this.listaEncargadosObsr = listaEncargadosObsr;
    }

    public Encargado getSelectedEncargado() {
        return selectedEncargado;
    }

    public void setSelectedEncargado(Encargado selectedEncargado) {
        this.selectedEncargado = selectedEncargado;
    }

    public TarjetaResponsabilidad getSelectedTarjeta() {
        return selectedTarjeta;
    }

    public void setSelectedTarjeta(TarjetaResponsabilidad selectedTarjeta) {
        this.selectedTarjeta = selectedTarjeta;
    }

    public Proveedor getSelectedProveedor() {
        return selectedProveedor;
    }

    public void setSelectedProveedor(Proveedor selectedProveedor) {
        this.selectedProveedor = selectedProveedor;
    }

    public JLabel getSelectedProveedorLabel(){
        return selectedProveedorLabel;
    }

    public JLabel getSelectedEncargadoLabel(){
        return selectedEncargadoLabel;
    }

    public boolean isFacturaButtonSelected() {
        return facturaButtonSelected;
    }

    public void setFacturaButtonSelected(boolean facturaButtonSelected) {
        this.facturaButtonSelected = facturaButtonSelected;
    }
    
    public Vista getVista(){
        return this.vista;
    }

    public boolean isTableEncargadosSelected() {
        return tableEncargadosSelected;
    }

    public void setTableEncargadosSelected(boolean tableEncargadoSelected) {
        this.tableEncargadosSelected = tableEncargadoSelected;
    }

    public boolean isTableTarjetasSelected() {
        return tableTarjetasSelected;
    }

    public void setTableTarjetasSelected(boolean tableTarjetasSelected) {
        this.tableTarjetasSelected = tableTarjetasSelected;
    }

    public boolean isTableProveedoresSelected() {
        return tableProveedoresSelected;
    }

    public void setTableProveedoresSelected(boolean tableProveedoresSelected) {
        this.tableProveedoresSelected = tableProveedoresSelected;
    }

    public JTextField getNoFacturaTextField() {
        return noFacturaTextField;
    }

    public void setNoFacturaTextField(JTextField noFacturaTextField) {
        this.noFacturaTextField = noFacturaTextField;
    }
    
    private void iniciarlizar(){
        this.controladorEncargado = new ControladorEncargado();
        this.controladorTarjeta = new ControladorTarjetaResponsabilidad();
        this.controladorProveedor = new ControladorProveedor();
        this.listaEncargados = new LinkedList<>();
        this.listaEncargadosObsr = ObservableCollections.observableList(listaEncargados);
        this.listaProveedores = new LinkedList<>();
        this.listaProveedoresObsr = ObservableCollections.observableList(listaProveedores);
        this.listaTarjetas = new LinkedList<>();
        this.listaTarjetasObsr = ObservableCollections.observableList(listaTarjetas);
    }

    public JTextField getNoOrdenCompraTextField() {
        return noFacturaTextField;
    }

    public void setNoOrdenCompraTextField(JTextField NoOrdenCompraTextField) {
        this.noFacturaTextField = NoOrdenCompraTextField;
    }

    public Factura getSelectedFactura() {
        return selectedFactura;
    }

    public void setSelectedFactura(Factura selectedFactura) {
        this.selectedFactura = selectedFactura;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarButton;
    private javax.swing.JButton actualizarTablasButton;
    private javax.swing.JButton cambiarFacturaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JTextField noFacturaTextField;
    private javax.swing.JPanel panelValidacion;
    private javax.swing.JLabel selectedEncargadoLabel;
    private javax.swing.JLabel selectedProveedorLabel;
    private javax.swing.JTable tablaEncargado;
    private javax.swing.JLabel tablaEncargados;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTable tablaTarjetas;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
