/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pss1inventarioscunoc.frontend.vistas.inventarios;

import javax.swing.JOptionPane;
import pss1inventarioscunoc.backend.controladores.ControladorInventario;
import pss1inventarioscunoc.backend.pojos.Inventario;

/**
 *
 * @author jesfrin
 */
public class ModificacionInventarioJDialog extends javax.swing.JDialog {

    private Inventario inventario;
    private ControladorInventario controladorInventario;

    /**
     * Creates new form ModificacionInventarioJDialog
     */
    public ModificacionInventarioJDialog(java.awt.Frame parent, boolean modal,Inventario inventario) {
        super(parent, modal);
        this.inventario = inventario;
        initComponents();
        colocarValoresDeInventario();
        controladorInventario = new ControladorInventario();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        fechaIniciojDateChooser1 = new com.toedter.calendar.JDateChooser();
        descripcionTextField10 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        fechaFinaljDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        unidadAcademiacaTextField11 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        modificarButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 119, 180));
        jPanel1.setFocusCycleRoot(true);

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel20.setText("fecha Inicio*:");

        descripcionTextField10.setBackground(new java.awt.Color(255, 255, 255));
        descripcionTextField10.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        descripcionTextField10.setForeground(new java.awt.Color(0, 0, 102));
        descripcionTextField10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel22.setText("descripcion*:");

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel23.setText("fecha final*:");

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel24.setText("unidad academica*:");

        unidadAcademiacaTextField11.setBackground(new java.awt.Color(255, 255, 255));
        unidadAcademiacaTextField11.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        unidadAcademiacaTextField11.setForeground(new java.awt.Color(0, 0, 102));
        unidadAcademiacaTextField11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel25.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel25.setText("Modificacion de Inventarios");

        modificarButton2.setBackground(new java.awt.Color(255, 153, 0));
        modificarButton2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        modificarButton2.setText("Modificar");
        modificarButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        modificarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(unidadAcademiacaTextField11)
                    .addComponent(fechaFinaljDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addComponent(fechaIniciojDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descripcionTextField10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(modificarButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(173, 173, 173))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(fechaIniciojDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(fechaFinaljDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel23))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(descripcionTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(unidadAcademiacaTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(modificarButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarButton2ActionPerformed
        Inventario inv = controladorInventario.validarDatosDeInventario(this.fechaIniciojDateChooser1.getDate(), this.descripcionTextField10.getText(), this.unidadAcademiacaTextField11.getText(), this.fechaFinaljDateChooser2.getDate());
        if(inv!=null){
            inv.setNumero(inventario.getNumero());
            if(controladorInventario.actualizarInventario(inv)){
                JOptionPane.showMessageDialog(this, "Se ha actualizado el Inventario");
                this.dispose();;
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo actualizar el inventario", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_modificarButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField descripcionTextField10;
    private com.toedter.calendar.JDateChooser fechaFinaljDateChooser2;
    private com.toedter.calendar.JDateChooser fechaIniciojDateChooser1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificarButton2;
    private javax.swing.JTextField unidadAcademiacaTextField11;
    // End of variables declaration//GEN-END:variables

    public void colocarValoresDeInventario() {
        this.fechaIniciojDateChooser1.setDate(this.inventario.getFechaInicio());
        this.fechaFinaljDateChooser2.setDate(this.inventario.getFechaFinalizacion());
        this.descripcionTextField10.setText(this.inventario.getDescripcion());
        this.unidadAcademiacaTextField11.setText(this.inventario.getUnidadAcademica());
    }

}
